version: "1.0.0.{build}"
environment:
  nodejs_version: 7

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm i -g gulp
  - npm i -g tfx-cli
  - npm i

build: off

test_script:
  - node --version
  - gulp package 

artifacts:
  - path: '_packages\stefankert.codesigning-1.0.0.vsix'
cache:
  - node_modules -> package.json          
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: YlLQ7g+X0lFS4+Y+uDKGGhLUicUm2wUmG9NJQqOGEDPP6ZKqp0Z8ZAOPFwKL7TXZ
    artifact:  '_packages\stefankert.codesigning-1.0.0.vsix'
    prerelease: true
    force_update: true
    on:       
      appveyor_repo_tag: true