version: "{build}"
environment:
  nodejs_version: 7

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - set PATH=%APPDATA%\npm;%PATH%

build: off

test-script:
  - node --version
  - gulp package

artifacts:
  - path: '**\*.vsix'
cache:
  - "%LOCALAPPDATA%\\npm"
  - node_modules -> package.json          