trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/*

pool:
  vmImage: windows-2019

steps:
- powershell: |
    npm install -g tfx-cli
    npm install -g typescript
    npm install -g mocha
    npm install -g gulp
    npm install
  displayName: 'npm install prerequisites'

- powershell: gulp package
  displayName: 'npm install and build'

- powershell: npm run test
  displayName: 'Run Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'

- task: CopyFiles@1
  displayName: Copy Files to - $(build.artifactstagingdirectory)
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
      **\*.vsix
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
